# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false

  config.vm.define 'test.local' do |vagrant|
    vagrant.vm.box = 'bento/ubuntu-16.04'
    vagrant.vm.network 'private_network', ip: '172.16.3.10'
    vagrant.vm.network 'forwarded_port', guest: 22, host: 2210, id: 'ssh'
  end
end
